[tool.poetry]
name = "docker-talk"
version = "0.1.0"
description = ""
authors = ["Josh Finnie <josh@jfin.us>"]

[tool.poetry.dependencies]
python = "^3.6"
left-pad = "^0.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
